Header header                         # map timestamp and frame id

Ontology ontology                     # ontology of this map

string id                             # unique map identifier
string type                           # map type

Address address                       # address of this map

Object[] objects                      # list of objects in this map
ActionOnObject[] actions              # list of actions on the map objects

ObjectProperty[] object_properties    # list of object properties of this map
DataProperty[] data_properties        # list of data properties of this map
