Ontology ontology                   # ontology of this mission

string id                           # unique mission identifier
string type                         # mission type

string map                          # map identifier of this mission

Task[] tasks                        # list of tasks of this mission

ObjectProperty[] object_properties  # list of object properties of this mission
DataProperty[] data_properties      # list of data properties of this mission
